development:
  access_key_id: AKIAJP3XTYOFNXJG4XCQ
  secret_access_key: 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
  simple_db_consistent_reads: false

production:
  access_key_id: AKIAJP3XTYOFNXJG4XCQ
  secret_access_key: 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
  simple_db_consistent_reads: true
